"""Add created_at and is_active fields

Revision ID: 08ace3d14da6
Revises: f22b10ac170e
Create Date: 2024-09-26 22:33:07.798992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ace3d14da6'
down_revision = 'f22b10ac170e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_log', schema=None) as batch_op:
        batch_op.alter_column('user_input',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_log', schema=None) as batch_op:
        batch_op.alter_column('user_input',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
