"""New col

Revision ID: cb243ede3ab4
Revises: 08ace3d14da6
Create Date: 2024-09-27 20:58:14.121570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb243ede3ab4'
down_revision = '08ace3d14da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_model', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_log', schema=None) as batch_op:
        batch_op.drop_column('ai_model')

    # ### end Alembic commands ###
